version: "3.9"

services:
  update-gdrive-files:
    restart: unless-stopped
    build: .
    container_name: update-gdrive-files
    command:
      - /bin/bash
      - -c
      - |
        cd /mnt_src
        python fetch_new_files.py -i 6

    volumes:
      - ./gdrive_insights:/mnt_src

  # sync-gdrive-revisions:
  #   restart: unless-stopped
  #   build: .
  #   container_name: sync-gdrive-revisions
  #   command:
  #       - /bin/bash
  #       - -c
  #       - |
  #           cd /mnt_src
  #           ????
  #   volumes:
  #     - ./gdrive_insights:/mnt_src
