version: "3.9"

services:
  update-gdrive-files:
    restart: unless-stopped
    build: .
    container_name: update-gdrive-files
    command:
      - /bin/bash
      - -c
      - |
        cd /mnt_src
        # run `fetch_new_files.py` every 6 hours
        python fetch_new_files.py -i 6

    volumes:
      - ./gdrive_insights:/mnt_src
      - ./gdrive_insights/config/postgres.cfg:/usr/local/lib/python3.9/site-packages/gdrive_insights/config/postgres.cfg
      - ./gdrive_insights/client_id.json:/mnt_src/gdrive_insights/client_id.json
      - ./gdrive_insights/storage.json:/mnt_src/gdrive_insights/storage.json

    environment:
      - GDRIVE_INSIGHTS_REPO=/mnt_src

  # sync-gdrive-revisions:
  #   restart: unless-stopped
  #   build: .
  #   container_name: sync-gdrive-revisions
  #   command:
  #       - /bin/bash
  #       - -c
  #       - |
  #           cd /mnt_src
  #           ????
  #   volumes:
  #     - ./gdrive_insights:/mnt_src
